// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrTpiR2ITZZ9EgT_JyRDgBUKWHd9HcDwI',
    appId: '1:469611781873:web:437c4fa61b97863a9ad350',
    messagingSenderId: '469611781873',
    projectId: 'movies-app-93def',
    authDomain: 'movies-app-93def.firebaseapp.com',
    storageBucket: 'movies-app-93def.firebasestorage.app',
    measurementId: 'G-Q440X434ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD62gTxddVXpasi6D_a5VEHIn--ViMtlQA',
    appId: '1:469611781873:android:ca72082949b2e1969ad350',
    messagingSenderId: '469611781873',
    projectId: 'movies-app-93def',
    storageBucket: 'movies-app-93def.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWK3Kl2JSSNa4HgoGIenwEO1feu49hyX0',
    appId: '1:469611781873:ios:4e04fa7256161b009ad350',
    messagingSenderId: '469611781873',
    projectId: 'movies-app-93def',
    storageBucket: 'movies-app-93def.firebasestorage.app',
    androidClientId:
        '469611781873-05u9blgn65ldgl2sbrhvs9ngi5hk1qfm.apps.googleusercontent.com',
    iosClientId:
        '469611781873-f1c6b4t61h9r8u3vear5d5i18npvgklj.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWK3Kl2JSSNa4HgoGIenwEO1feu49hyX0',
    appId: '1:469611781873:ios:4e04fa7256161b009ad350',
    messagingSenderId: '469611781873',
    projectId: 'movies-app-93def',
    storageBucket: 'movies-app-93def.firebasestorage.app',
    androidClientId:
        '469611781873-05u9blgn65ldgl2sbrhvs9ngi5hk1qfm.apps.googleusercontent.com',
    iosClientId:
        '469611781873-f1c6b4t61h9r8u3vear5d5i18npvgklj.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
